-- Заполнение таблицы wmiproperties

INSERT INTO `tbInventoryProperty` (`id`, `wmiclass_id`, `name`, `property_type`, `description`) VALUES
(1,	11,	'DeviceID',	'String',	''),
(2,	11,	'Architecture',	'UInt16',	''),
(3,	11,	'MaxClockSpeed',	'UInt32',	''),
(4,	11,	'Name',	'String',	''),
(5,	1,	'Name',	'String',	''),
(6,	1,	'Version',	'String',	''),
(7,	1,	'Manufacturer',	'String',	''),
(8,	1,	'ReleaseDate',	'DateTime',	''),
(13,	8,	'Name',	'String',	''),
(14,	8,	'BuildNumber',	'String',	''),
(15,	8,	'Caption',	'String',	''),
(16,	8,	'OSProductSuite',	'UInt32',	''),
(17,	8,	'OSLanguage',	'UInt32',	''),
(18,	8,	'OtherTypeDescription',	'String',	''),
(19,	8,	'ProductType',	'UInt32',	''),
(20,	8,	'SerialNumber',	'String',	''),
(21,	8,	'ServicePackMajorVersion',	'UInt16',	''),
(22,	8,	'ServicePackMinorVersion',	'UInt16',	''),
(23,	8,	'Version',	'String',	''),
(24,	4,	'DeviceID',	'String',	''),
(25,	4,	'Name',	'String',	''),
(26,	4,	'Caption',	'String',	''),
(27,	4,	'Manufacturer',	'String',	''),
(28,	4,	'Model',	'String',	''),
(29,	4,	'InterfaceType',	'String',	''),
(30,	4,	'Partitions',	'UInt32',	''),
(31,	4,	'Size',	'UInt64',	''),
(32,	5,	'DeviceID',	'String',	''),
(33,	5,	'Name',	'String',	''),
(34,	5,	'DriveType',	'UInt32',	''),
(35,	5,	'VolumeName',	'String',	''),
(36,	5,	'FileSystem',	'String',	''),
(37,	5,	'Size',	'UInt64',	''),
(38,	5,	'FreeSpace',	'UInt64',	''),
(39,	7,	'Index',	'UInt32',	''),
(40,	7,	'Caption',	'String',	''),
(41,	7,	'Description',	'String',	''),
(42,	7,	'DHCPEnabled',	'Boolean',	''),
(43,	7,	'DHCPLeaseExpires',	'DateTime',	''),
(44,	7,	'DHCPLeaseObtained',	'DateTime',	''),
(45,	7,	'DHCPServer',	'String',	''),
(46,	7,	'DNSDomain',	'String',	''),
(47,	7,	'DNSEnabledForWINSResolution',	'Boolean',	''),
(48,	7,	'DNSHostName',	'String',	''),
(49,	7,	'DomainDNSRegistrationEnabled',	'Boolean',	''),
(50,	7,	'IPAddress',	'String',	''),
(51,	7,	'IPFilterSecurityEnabled',	'Boolean',	''),
(52,	7,	'IPPortSecurityEnabled',	'Boolean',	''),
(53,	7,	'WINSEnableLMHostsLookup',	'Boolean',	''),
(54,	7,	'WINSHostLookupFile',	'String',	''),
(55,	7,	'WINSPrimaryServer',	'String',	''),
(56,	7,	'WINSScopeID',	'String',	''),
(57,	7,	'WINSSecondaryServer',	'String',	''),
(58,	6,	'DeviceID',	'String',	''),
(59,	6,	'Index',	'UInt32',	''),
(60,	6,	'Name',	'String',	''),
(61,	6,	'Caption',	'String',	''),
(62,	6,	'Description',	'String',	''),
(63,	6,	'Manufacturer',	'String',	''),
(64,	6,	'ProductName',	'String',	''),
(65,	6,	'MACAddress',	'String',	''),
(66,	6,	'Speed',	'UInt64',	''),
(67,	6,	'MaxSpeed',	'UInt64',	''),
(68,	6,	'NetConnectionStatus',	'UInt16',	''),
(69,	6,	'NetConnectionID',	'String',	''),
(70,	12,	'DeviceID',	'String',	''),
(71,	12,	'Name',	'String',	''),
(72,	12,	'Manufacturer',	'String',	''),
(73,	13,	'DeviceID',	'String',	''),
(74,	13,	'Description',	'String',	''),
(75,	13,	'AdapterRAM',	'UInt32',	''),
(76,	13,	'DriverDate',	'DateTime',	''),
(77,	13,	'VideoModeDescription',	'String',	''),
(78,	3,	'DeviceID',	'String',	''),
(79,	3,	'Name',	'String',	''),
(80,	3,	'MonitorManufacturer',	'String',	''),
(81,	3,	'PixelsPerXLogicalInch',	'UInt32',	''),
(82,	3,	'PixelsPerYLogicalInch',	'UInt32',	''),
(83,	3,	'ScreenHeight',	'UInt32',	''),
(84,	3,	'ScreenWidth',	'UInt32',	''),
(85,	2,	'Name',	'String',	''),
(86,	2,	'Manufacturer',	'String',	''),
(87,	2,	'Model',	'String',	''),
(88,	2,	'TotalPhysicalMemory',	'UInt64',	''),
(89,	10,	'DeviceID',	'String',	''),
(90,	10,	'Name',	'String',	''),
(91,	10,	'Local',	'Boolean',	''),
(92,	10,	'Network',	'Boolean',	''),
(93,	10,	'Location',	'String',	''),
(94,	10,	'Comment',	'String',	''),
(95,	10,	'DriverName',	'String',	''),
(96,	10,	'Shared',	'Boolean',	''),
(97,	10,	'ShareName',	'String',	''),
(103,	15,	'Caption',	'String',	''),
(104,	15,	'Name',	'String',	''),
(105,	15,	'DeviceLocator',	'String',	''),
(106,	15,	'Capacity',	'UInt32',	''),
(107,	15,	'Speed',	'UInt16',	''),
(108,	15,	'MemoryType',	'UInt16',	''),
(109,	15,	'Manufacturer',	'String',	''),
(110,	13,	'DriverVersion',	'String',	''),
(111,	11,	'NumberOfCores',	'UInt16',	''),
(112,	11,	'NumberOfLogicalProcessors',	'UInt16',	''),
(113,	16,	'Manufacturer',	'String',	''),
(114,	16,	'Product',	'String',	''),
(115,	16,	'Model',	'String',	''),
(116,	16,	'SerialNumber',	'String',	''),
(117,	8,	'OSArchitecture',	'String',	''),
(118,	7,	'IPEnabled',	'Boolean',	''),
(119,	17,	'DriverName',	'String',	''),
(120,	17,	'Manufacturer',	'String',	''),
(121,	17,	'Name',	'String',	''),
(122,	17,	'ProtocolSupported',	'UInt16',	''),
(123,	17,	'Status',	'String',	''),
(124,	17,	'StatusInfo',	'UInt16',	''),
(126,	18,	'DriverName',	'String',	''),
(127,	18,	'Manufacturer',	'String',	''),
(128,	18,	'Name',	'String',	''),
(129,	18,	'ProtocolSupported',	'UInt16',	''),
(130,	18,	'Status',	'String',	''),
(131,	18,	'StatusInfo',	'UInt16',	''),
(132,	19,	'Caption',	'String',	''),
(133,	19,	'Description',	'String',	''),
(134,	19,	'DeviceID',	'String',	''),
(135,	19,	'Manufacturer',	'String',	''),
(136,	19,	'Name',	'String',	''),
(137,	19,	'ProtocolSupported',	'UInt16',	''),
(138,	19,	'Status',	'String',	''),
(139,	19,	'StatusInfo',	'UInt16',	''),
(140,	19,	'PNPDeviceID',	'String',	''),
(141,	20,	'Caption',	'String',	''),
(142,	20,	'Description',	'String',	''),
(143,	20,	'DeviceID',	'String',	''),
(145,	20,	'Name',	'String',	''),
(146,	20,	'ProtocolCode',	'UInt16',	''),
(147,	20,	'Status',	'String',	''),
(148,	20,	'StatusInfo',	'UInt16',	''),
(149,	20,	'PNPDeviceID',	'String',	''),
(150,	21,	'Caption',	'String',	''),
(151,	21,	'Description',	'String',	''),
(152,	21,	'DeviceID',	'String',	''),
(153,	21,	'Manufacturer',	'String',	''),
(154,	21,	'Name',	'String',	''),
(155,	21,	'HardwareType',	'String',	'Type of hardware used for the Windows pointing device.'),
(156,	21,	'Status',	'String',	'Current status of the object. Various operational and nonoperational statuses can be defined. Operational statuses include: OK, Degraded, and Pred Fail (an element, such as a SMART-enabled hard disk drive, may be functioning properly but predicting a failure in the near future). Nonoperational statuses include: Error, Starting, Stopping, and Service. The latter, Service, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. Not all such work is online, yet the managed element is neither OK nor in one of the other states.'),
(157,	21,	'StatusInfo',	'UInt16',	''),
(158,	21,	'PNPDeviceID',	'String',	''),
(159,	21,	'PointingType',	'UInt16',	''),
(160,	21,	'NumberOfButtons',	'UInt16',	''),
(161,	21,	'QuadSpeedThreshold',	'String',	''),
(162,	21,	'Resolution',	'String',	''),
(163,	21,	'SampleRate',	'String',	''),
(164,	22,	'Caption',	'String',	''),
(165,	22,	'Description',	'String',	''),
(166,	22,	'DeviceID',	'String',	''),
(168,	22,	'Name',	'String',	''),
(170,	22,	'Status',	'String',	''),
(171,	22,	'StatusInfo',	'UInt16',	''),
(172,	22,	'PNPDeviceID',	'String',	''),
(173,	23,	'Caption',	'String',	''),
(174,	23,	'Description',	'String',	''),
(175,	23,	'DeviceID',	'String',	''),
(177,	23,	'Name',	'String',	''),
(179,	23,	'Status',	'String',	''),
(180,	23,	'StatusInfo',	'UInt16',	''),
(181,	23,	'PNPDeviceID',	'String',	''),
(182,	24,	'Caption',	'String',	''),
(183,	24,	'Description',	'String',	''),
(184,	24,	'DeviceID',	'String',	''),
(186,	24,	'Name',	'String',	''),
(188,	24,	'Status',	'String',	''),
(189,	24,	'StatusInfo',	'UInt16',	''),
(190,	24,	'PNPDeviceID',	'String',	''),
(191,	8,	'InstallDate',	'DateTime',	''),
(192,	2,	'Description',	'String',	''),
(193,	8,	'Description',	'String',	''),
(194,	25,	'UUID',	'String',	''),
(195,	6,	'GUID',	'String',	''),
(196,	2,	'PCSystemType',	'UInt16',	''),
(197,	4,	'PNPDeviceID',	'String',	''),
(198,	26,	'Antecedent',	'String',	''),
(199,	26,	'Dependent',	'String',	''),
(200,	27,	'Antecedent',	'String',	''),
(201,	27,	'Dependent',	'String',	''),
(202,	28,	'Name',	'String',	''),
(203,	28,	'MaxCapacity',	'UInt32',	''),
(204,	28,	'MemoryDevices',	'UInt16',	''),
(205,	15,	'BankLabel',	'String',	''),
(206,	11,	'Manufacturer',	'String',	''),
(207,	11,	'Description',	'String',	''),
(208,	29,	'Name',	'String',	''),
(209,	29,	'BatteryStatus',	'Uint16',	'Description of the battery s charge status. The value 10 (Undefined) is not valid in the Common Information Model (CIM) schema because in Desktop Management Interface (DMI) it indicates that no battery is installed. In this case, this object should not be instantiated.'),
(210,	29,	'Caption',	'String',	''),
(211,	29,	'DesignCapacity',	'Uint32',	'Design capacity of the battery in milliwatt-hours. If this property is not supported, enter 0 (zero).'),
(212,	29,	'DesignVoltage',	'Uint64',	'Design voltage of the battery in millivolts. If this attribute is not supported, enter 0 (zero).'),
(213,	29,	'ManufactureDate',	'String',	''),
(214,	29,	'Manufacturer',	'String',	''),
(215,	29,	'MaxBatteryError',	'Uint16',	'Difference between the highest estimated amount of energy left in the battery and the current amount reported by the battery.'),
(216,	29,	'TimeOnBattery',	'Uint32',	''),
(217,	29,	'TimeToFullCharge',	'Uint32',	''),
(218,	29,	'Location',	'String',	'Physical location of the battery. This property is filled by the computer manufacturer.'),
(219,	29,	'Status',	'String',	''),
(220,	30,	'Name',	'String',	'Defines the label by which the object is known. When subclassed, the property can be overridden to be a key property.'),
(221,	30,	'Caption',	'String',	'Short description of the object a one-line string.'),
(222,	30,	'Status',	'String',	'Current status of the object. Various operational and nonoperational statuses can be defined. Operational statuses include: OK, Degraded, and Pred Fail (an element, such as a SMART-enabled hard disk drive, may be functioning properly but predicting a failure in the near future). Nonoperational statuses include: Error, Starting, Stopping, and Service. The latter, Service, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. Not all such work is online, yet the managed element is neither OK nor in one of the other states.'),
(223,	30,	'DesignCapacity',	'Uint32',	'Design capacity of the battery in milliwatt-hours. If the property is not supported, enter 0 (zero).'),
(224,	30,	'DesignVoltage',	'Uint64',	'Design voltage of the battery in millivolts. If the attribute is not supported, enter 0 (zero).'),
(225,	30,	'EstimatedChargeRemaining',	'Uint16',	'Estimate of the percentage of full charge remaining.'),
(226,	30,	'EstimatedRunTime',	'Uint32',	'Estimate in minutes of the time to battery charge depletion under the present load conditions if the utility power is off, or lost and remains off, or a laptop is disconnected from a power source.'),
(227,	30,	'FullChargeCapacity',	'Uint32',	'Full charge capacity of the battery in milliwatt-hours. Comparison of the value to the DesignCapacity property determines when the battery requires replacement. A batterys end of life is typically when the FullChargeCapacity property falls below 80% of the DesignCapacity property. If the property is not supported, enter 0 (zero).'),
(228,	30,	'ErrorDescription',	'String',	'Free-form string that supplies more information about the error recorded in LastErrorCode property, and information about any corrective actions that may be taken.'),
(229,	2,	'AdminPasswordStatus',	'Uint16',	'System hardware security settings for administrator password status.'),
(230,	2,	'BootupState',	'String',	'System is started. Fail-safe boot bypasses the user startuo files also called SafeBoot.'),
(231,	2,	'ChassisBootupState',	'Uint16',	'This value comes from the Boot-up State member of the System Enclosure or Chassis structure in the SMBIOS information.'),
(232,	4,	'Status',	'String',	'Current status of the object. Various operational and nonoperational statuses can be defined. Operational statuses include: OK, Degraded, and Pred Fail (an element, such as a SMART-enabled hard disk drive, may be functioning properly but predicting a failure in the near future). Nonoperational statuses include: Error, Starting, Stopping, and Service. The latter, Service, could apply during mirror-resilvering of a disk, reload of a user permissions list, or other administrative work. Not all such work is online, yet the managed element is neither OK nor in one of the other states.'),
(801,	81,	'GroupComponent',	'String',	''),
(802,	81,	'PartComponent',	'String',	''),
(803,	80,	'Status',	'String',	''),
(804,	80,	'Caption',	'String',	''),
(805,	80,	'PasswordExpires',	'Boolean',	''),
(806,	80,	'Description',	'String',	''),
(807,	80,	'Disabled',	'Boolean',	''),
(808,	80,	'Domain',	'String',	''),
(809,	80,	'FullName',	'String',	''),
(810,	80,	'LocalAccount',	'Boolean',	''),
(811,	80,	'Lockout',	'Boolean',	''),
(812,	80,	'Name',	'String',	''),
(813,	80,	'PasswordChangeable',	'Boolean',	''),
(814,	80,	'PasswordRequired',	'Boolean',	''),
(815,	80,	'SID',	'String',	''),
(901,	90,	'Name',	'String',	''),
(902,	90,	'Version',	'String',	''),
(903,	90,	'Vendor',	'String',	''),
(904,	90,	'InstallDate',	'DateTime',	''),
(905,	90,	'IdentifyingNumber',	'String',	''),
(910,	91,	'Name',	'String',	''),
(911,	91,	'ApplicationId',	'String',	''),
(912,	91,	'LicenseStatus',	'UInt16',	''),
(913,	91,	'ProductKeyChannel',	'String',	''),
(920,	92,	'InstanceName',	'String',	''),
(921,	92,	'PredictFailure',	'Boolean',	''),
(922,	92,	'Reason',	'UInt32',	''),
(930,	93,	'Description',	'String',	'A textual description of the object.'),
(931,	93,	'HotFixID',	'String',	'Indicates when the object was installed. Lack of a value does not indicate that the object is not installed.'),
(932,	93,	'InstalledOn',	'DateTime',	'This property may use different formats, depending on when the QuickFix was installed. Most systems use a standard date format, such as \"23-10-2013\". However, some systems may return a 64-bit hexidecimal value in the Win32 FILETIME format.'),
(933,	93,	'Status',	'String',	'String that indicates the current status of the object. Operational and non-operational status can be defined. Operational status can include \"OK\", \"Degraded\", and \"Pred Fail\". \"Pred Fail\" indicates that an element is functioning properly, but is predicting a failure (for example, a SMART-enabled hard disk drive).'),
(940,	94,	'Name',	'String',	''),
(941,	94,	'DeviceID',	'String',	''),
(942,	94,	'ConfigManagerErrorCode',	'UInt32',	'Win32 Configuration Manager error code.');
